-- select
--   concat(instance_id, ' [', region, '/', account_id, ']') as title,
--   instance_id,
--   region,
--   _ctx ->> 'connection_name' as cred
-- from
--   aws_ec2_instance
-- where
--   date_part('day', now()-launch_time) > ${var.ec2_instance_age_max_days}
--   and instance_state in ('running', 'pending', 'rebooting');